config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "events#index"

  resources :events do
    resource :register, only: %i[create], module: :events, controller: :register

    collection do
      resources :all, as: :events_all, only: %i[index], module: :events, controller: :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: "user_id"

  has_many :participations, dependent: :destroy

  has_many :users, through: :participations

  validates :title, presence: true

  def available_seats
    return if limit.nil?

    limit - participations.count
  end

  def available_seats?
    limit.nil? || (limit - participations.count) > 0
  end
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :event, uniqueness: { scope: :user_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, class_name: "Event", inverse_of: :creator, dependent: :destroy

  has_many :participations, dependent: :destroy

  has_many :events, through: :participations

  enum :role, { participant: 0, organizer: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :authenticate_user!
end

app/controllers/events/all_controller.rb
module Events
  class AllController < ApplicationController
    include Pundit::Authorization

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    def index
      authorize %i[events all]

      @events = Event.all
    end

    private

      def user_not_authorized
        flash[:alert] = "You are not authorized to perform this action."
        redirect_back_or_to(root_path)
      end
  end
end

app/controllers/events/register_controller.rb
module Events
  class RegisterController < ApplicationController
    include Pundit::Authorization

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    def create
      event = Event.find(params[:event_id])
      authorize %i[events register]

      respond_to do |format|
        if Events::Register.new(event: event).call(user: current_user)
          format.html { redirect_to events_path, notice: "User was successfully registered to the event '#{event.title}'." }
          format.json { render :show, status: :created, location: event }
        else
          format.html { redirect_to events_path, notice: "User cannot be registered to the event '#{event.title}'." }
          format.json { render :show, status: :unprocessable_entity, location: event }
        end
      end
    end

    private

      def user_not_authorized
        flash[:alert] = "You are not authorized to perform this action."
        redirect_back_or_to(root_path)
      end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    authorize Event

    @events = policy_scope(Event)
  end

  # GET /events/1 or /events/1.json
  def show
    authorize @event
  end

  # GET /events/new
  def new
    authorize Event

    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    authorize @event
  end

  # POST /events or /events.json
  def create
    authorize Event

    @event = policy_scope(Event).new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    authorize @event

    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    authorize @event

    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_path, status: :see_other, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_back_or_to(root_path)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = policy_scope(Event).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :limit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Title:</strong>
    <%= event.title %>
  </p>

  <p>
    <strong>Creator:</strong>
    <%= render partial: 'users/user', object: event.creator %>
  </p>

  <p>
    <strong>Limit:</strong>
    <% if event.limit.nil? %>
      No Limit
    <% else %>
      <%= event.limit %> (available: <%= event.available_seats %>)
    <% end %>
  </p>

  <% if policy(%i[events register]).create? %>
    <% if current_user.participations.find_by(event: event).blank? %>
      <p>
        <%= button_to 'Register', event_register_path(event_id: event.id, method: :post) %>
      </p>
    <% else %>
      <p class="notice">
        Registered!
      </p>
    <% end %>
  <% end %>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div class="alert">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :limit, style: "display: block" %>
    <%= form.number_field :limit %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/all/index.html.erb
<% content_for :title, "All Events" %>

<h1>All Events</h1>

<% if policy(Event).index? %>
  <%= link_to "My Events", events_path %>
<% end %>

<div id="events">
  <% if @events.empty? %>
    <p>No events.</p>
  <% end %>

  <% @events.each do |event| %>
    <div class="event">
      <%= render partial: 'events/event', object: event %>

      <% if policy(event).show? %>
        <p>
         <%= link_to "Show this event", event %>
        </p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<% content_for :title, "Editing event" %>

<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <% if policy(@event).show? %>
    <%= link_to "Show this event", @event %>
  <% end %>

  <% if policy(Event).index? %>
    <%= link_to "Back to events", events_path %>
  <% end %>
</div>

app/views/events/index.html.erb
<% content_for :title, "Events" %>

<h1>Events</h1>

<div id="events">
  <% if @events.empty? %>
    <p>No events.</p>
  <% end %>

  <% @events.each do |event| %>
    <%= render event %>

    <% if policy(event).show? %>
      <p>
        <%= link_to "Show this event", event %>
      </p>
    <% end %>
  <% end %>
</div>

<% if policy(Event).new? %>
  <%= link_to "New event", new_event_path %>
<% end %>

app/views/events/new.html.erb
<% content_for :title, "New event" %>

<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <% if policy(Event).index? %>
    <%= link_to "Back to events", events_path %>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="event">
  <%= render @event %>

  <div>
    <strong>Participants:</strong>

    <% if @event.participations.empty? %>
      <p>No participants.</p>
    <% else %>
      <ul>
        <% @event.participations.map do |participation| %>
          <li>
            <%= render participation.user %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div style="border-top: 1px dashed #000; padding-top: .5rem">
    <% if policy(@event).edit? %>
      <%= link_to "Edit this event", edit_event_path(@event) %>
    <% end %>

    <% if policy(@event).destroy? %>
      <%= button_to "Destroy this event", @event, method: :delete %>
    <% end %>
  </div>
</div>

<div>
  <% if policy(Event).index? %>
    <%= link_to "Back to events", events_path %>
  <% end %>
</div>

app/views/home/index.html.erb
<h1>Home</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Event Registration System" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in? %>
      <%= link_to current_user.email, edit_user_registration_path %>
      <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete } %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/_user.html.erb
<%= user.email %>